### ISSUE TITLE
Install with pip

### ISSUE THREAD

**Issue by ZuluPro** [myles/django-contacts#24]
Hello @myles 
It seems that the current PyPi release is 0.5: https://pypi.python.org/pypi/django-contacts/
And maybe is a fork of yours (Home Page: http://github.com/asgardproject/django-contacts).

This version still uses `django.contrib.comments`,
So absolutely incompatible with newer versions.

Could we release a 0.6 with my changes ?

**Comment by myles** [comment]
Will do later this weekend. I'm currently traveling.

**Comment by myles** [comment]
Done.
