### ISSUE TITLE
django 1.10?

### ISSUE THREAD

**Issue by colost8rams** [myles/django-contacts#25]
Sorry, my son hit the enter key.

any plans to update to django 1.10?

**Comment by myles** [comment]
?

**Comment by colost8rams** [comment]
Sorry, my son hit the enter key.

any plans to update to django 1.10?

**Comment by myles** [comment]
I'm working on a complete redesign over in [django-rolodex](https://github.com/myles/django-rolodex) that will support Django 1.10.

@ZuluPro has taken over most of the development of this project.

**Comment by colost8rams** [comment]
thanks.
